### ISSUE TITLE
Remove commented-code & extra white-space

### ISSUE THREAD

**Issue by gokdayi** [gokdayi/mini-ticker-simulator#2]
## Expected Behavior
- Should not contain any commented-out code
- Should not contain any extra white-spaces

## Actual Behavior
- Currently, we have both comments & extra white-spaces

## Steps to Reproduce the Problem

  1. Take a look at `app.js`, you can see similar occurrences in other files, too.
  

## Specifications
> No specs for this one

**Comment by lucky-chap** [comment]
@gokdayi can I tackle this issue? If yes, then please assign it to me

**Comment by lucky-chap** [comment]
@gokdayi I have submitted a PR

**Comment by gokdayi** [comment]
@lucky-chap Thanks for the commit, even though it is a matter of preference, you should stick to the original indentation level all the time. For example, we use 2-space tabs in this project, 4 spaces is also a good one but as I said, the original indentation makes your changes get approved easier.

**Comment by lucky-chap** [comment]
Alright @gokdayi . I'd make sure to stick to your style of indentation

**Comment by gokdayi** [comment]
@lucky-chap Thank you so much 👍
